topics = [
	"/sensor/cam_front_60/compressed",
	"/sensor/cam_front_30/compressed",
	"/sensor/cam_front_left_120/compressed",
	"/sensor/cam_front_right_120/compressed",
	"/sensor/cam_back_left_120/compressed",
	"/sensor/cam_back_right_120/compressed",
    "/sensor/corr_imu",
#"/sensor/front_rslidar_packets",
#    "/sensor/front_rslidar_packets_difop",
    "/sensor/left_rslidar_packets",
    "/sensor/left_rslidar_packets_difop",
#    "/sensor/right_rslidar_packets",
#    "/sensor/right_rslidar_packets_difop",
#    "/sensor/left_down_rslidar_packets",
#    "/sensor/left_down_rslidar_packets_difop",
    "/sensor/right_down_rslidar_packets",
    "/sensor/right_down_rslidar_packets_difop",
    "/sensor/back_rslidar_packets",
    "/sensor/back_rslidar_packets_difop",
    "/sensor/gps",
    "/sensor/ins_pose",
    "/sensor/raw_imu",
    "/scene/tag",
    #"/sensor/ultrasonic",
    "/sensor/radar0_object",
    "/sensor/radar1_object",
    "/sensor/radar2_object",
    "/sensor/radar3_object",
    "/sensor/radar4_object",
	"/sensor/vehicle_report_common"
]
