list(PREPEND CMAKE_MODULE_PATH "/opt/ros/foxy/cmake")
list(PREPEND CMAKE_MODULE_PATH ${CMAKE_CURRENT_LIST_DIR})

list(PREPEND CMAKE_PREFIX_PATH "/opt/ros/foxy/cmake")
list(PREPEND CMAKE_PREFIX_PATH ${CMAKE_CURRENT_LIST_DIR})